//! Materializes every registered asset into the shared store and writes one
//! accessor per case into `OUT_DIR`.
//!
//! `src/defs/` and `src/registry.rs` compile only here — the library never sees
//! them, which is what keeps the encoders out of the target build.

#[path = "src/defs/mod.rs"]
mod defs;
#[path = "src/registry.rs"]
mod registry;
// `store` keeps the visibility it has in the library: it is the same source
// file, reached from two roots.
#[path = "src/store.rs"]
pub mod store;

use std::{
    collections::{HashSet, hash_map::DefaultHasher},
    fmt::Write as _,
    fs,
    hash::{Hash, Hasher},
    path::{Path, PathBuf},
};

use registry::AssetDef;

/// Source trees whose contents decide the generated bytes.
const HASHED_TREES: [&str; 1] = ["src/defs"];
/// Individual sources outside those trees that decide the same.
const HASHED_FILES: [&str; 3] = ["build.rs", "src/registry.rs", "src/store.rs"];

fn hash_rs_tree(dir: &Path, hasher: &mut DefaultHasher) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    let mut paths: Vec<_> = entries.flatten().map(|entry| entry.path()).collect();
    paths.sort();
    for path in paths {
        if path.is_dir() {
            hash_rs_tree(&path, hasher);
        } else if path.extension().is_some_and(|ext| ext == "rs") {
            if let Ok(bytes) = fs::read(&path) {
                path.to_string_lossy().hash(hasher);
                bytes.hash(hasher);
            }
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }
}

fn fingerprint() -> String {
    let mut hasher = DefaultHasher::new();
    for dir in HASHED_TREES {
        println!("cargo:rerun-if-changed={dir}");
        hash_rs_tree(Path::new(dir), &mut hasher);
    }
    for file in HASHED_FILES {
        fs::read(file)
            .unwrap_or_else(|error| panic!("kithara-fixtures: cannot read {file}: {error}"))
            .hash(&mut hasher);
        println!("cargo:rerun-if-changed={file}");
    }
    let hex = format!("{:016x}", hasher.finish());
    assert_eq!(
        hex.len(),
        store::FINGERPRINT_HEX_LEN,
        "kithara-fixtures: the namespace length the store publishes must match what this writes",
    );
    hex
}

/// Rejects two cases that would produce one accessor, before either is written.
fn resolve(defs: &[&'static AssetDef]) -> Vec<(String, String, &'static AssetDef)> {
    let mut seen: HashSet<String> = HashSet::new();
    let mut resolved = Vec::with_capacity(defs.len());
    for def in defs {
        let name = def.accessor_name();
        assert!(
            seen.insert(name.clone()),
            "kithara-fixtures: two asset cases share the accessor name `{name}`",
        );
        let id = store::asset_id(def.func, def.case);
        resolved.push((name, id, *def));
    }
    resolved
}

fn materialize(namespace: &Path, resolved: &[(String, String, &'static AssetDef)]) {
    for (name, id, def) in resolved {
        if store::read_entry(namespace, id, def.ext).is_some() {
            continue;
        }
        let _lock = store::lock_entry(namespace, id)
            .unwrap_or_else(|error| panic!("kithara-fixtures: lock for `{name}`: {error}"));
        if store::read_entry(namespace, id, def.ext).is_some() {
            continue;
        }
        let bytes = (def.build)();
        assert!(
            !bytes.is_empty(),
            "kithara-fixtures: `{name}` produced no bytes"
        );
        store::write_entry(namespace, id, def.ext, &bytes)
            .unwrap_or_else(|error| panic!("kithara-fixtures: write `{name}`: {error}"));
    }
}

fn codegen(namespace: &Path, resolved: &[(String, String, &'static AssetDef)]) -> String {
    let mut out = String::new();
    let mut manifest = String::new();
    for (name, id, def) in resolved {
        let entry = format!("ENTRY_{}", name.to_uppercase());
        let path = store::entry_path(namespace, id, def.ext);
        let path = path.to_str().unwrap_or_else(|| {
            panic!("kithara-fixtures: the store path for `{name}` is not valid UTF-8")
        });
        let content_type = def.content_type;
        let _ = write!(
            out,
            "static {entry}: crate::asset::AssetEntry = crate::asset::AssetEntry {{\n    \
             name: {name:?},\n    id: {id:?},\n    path: {path:?},\n    \
             content_type: {content_type:?},\n}};\n\n\
             #[must_use]\n\
             pub fn {name}() -> crate::asset::Asset {{\n    \
             static BYTES: ::std::sync::OnceLock<Vec<u8>> = ::std::sync::OnceLock::new();\n    \
             crate::asset::Asset::on_disk(&{entry}, &BYTES)\n}}\n\n",
        );
        let _ = writeln!(manifest, "    &{entry},");
    }
    let _ = write!(
        out,
        "/// Every asset this build materialized.\n\
         pub static MANIFEST: &[&crate::asset::AssetEntry] = &[\n{manifest}];\n",
    );
    out
}

fn main() {
    println!("cargo:rerun-if-env-changed={}", store::STORE_ENV);

    let defs: Vec<&AssetDef> = inventory::iter::<AssetDef>.into_iter().collect();
    assert!(
        !defs.is_empty(),
        "kithara-fixtures: the asset registry is empty; either `src/defs` declares no \
         `#[kithara::asset]`, or the registrations were dropped at link time",
    );
    let resolved = resolve(&defs);

    let fingerprint = fingerprint();
    let namespace = store::namespace(&store::root_from_env(), &fingerprint);
    materialize(&namespace, &resolved);

    // Written once per namespace so its mtime stays put on a no-op rerun; a
    // wiped store makes the declared path missing, which cargo reads as
    // changed and reruns this script.
    let stamp = namespace.join(".stamp");
    if fs::read(&stamp).ok().as_deref() != Some(fingerprint.as_bytes()) {
        fs::write(&stamp, fingerprint.as_bytes())
            .unwrap_or_else(|error| panic!("kithara-fixtures: write stamp: {error}"));
    }
    println!("cargo:rerun-if-changed={}", stamp.display());

    let out_dir =
        PathBuf::from(std::env::var_os("OUT_DIR").expect("invariant: cargo always sets OUT_DIR"));
    fs::write(out_dir.join("assets.rs"), codegen(&namespace, &resolved))
        .unwrap_or_else(|error| panic!("kithara-fixtures: write assets.rs: {error}"));
}
