[package]
name = "kithara-config"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Retained configuration values and composed configuration macros."

[dependencies]
kithara-derive = { workspace = true, features = ["config", "patch"] }

bon = { workspace = true }

[target.'cfg(all(not(target_arch = "wasm32"), not(target_os = "android")))'.dependencies]
kithara-workspace-hack = { version = "0.0.1-alpha5", path = "../kithara-workspace-hack" }

[dev-dependencies]
kithara-test-utils = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[lints]
workspace = true
