use std::fmt::Write as _;

use anyhow::{Result, bail, ensure};

use super::discover::{RegisteredField, Registration};

pub(super) fn render(registrations: &[Registration]) -> Result<String> {
    let delegates: Vec<_> = registrations
        .iter()
        .filter(|registration| registration.kind == "delegate" && registration.sdk)
        .collect();
    ensure!(
        !delegates.is_empty(),
        "no SDK config operations are registered"
    );
    let mut output = String::from(
        "// @generated by `just tooling xtask config project`; do not edit.\n\
         use kithara::play::{EqBandConfig, FilterKind, GainDb};\n\n\
         /// Filter response applied by one equalizer band.\n\
         #[derive(Clone, Copy, Debug, PartialEq, Eq)]\n\
         #[cfg_attr(any(feature = \"uniffi\", feature = \"uniffi-web\"), derive(uniffi::Enum))]\n\
         pub enum FfiEqFilterKind {\n\
         \x20\x20\x20\x20LowShelf,\n\
         \x20\x20\x20\x20Peaking,\n\
         \x20\x20\x20\x20HighShelf,\n\
         }\n\n",
    );
    for delegate in delegates {
        ensure!(
            delegate.package == "kithara-play"
                && delegate.property.as_deref() == Some("eq_layout")
                && delegate.hook.as_deref() == Some("set_eq_layout"),
            "unsupported SDK config operation {}::{:?}",
            delegate.owner,
            delegate.property
        );
        ensure!(delegate.fields.len() == 1, "EQ layout requires one input");
        let input = &delegate.fields[0];
        ensure!(
            compact(&input.rust_type) == "Vec<EqBandConfig>",
            "unsupported EQ layout input {}",
            input.rust_type
        );
        let retained = registrations
            .iter()
            .find(|registration| {
                registration.kind == "retained"
                    && registration.package == delegate.package
                    && registration.owner == "EqBandConfig"
            })
            .ok_or_else(|| anyhow::anyhow!("EqBandConfig is not registered"))?;
        render_record(&mut output, retained)?;
    }
    for retained in registrations
        .iter()
        .filter(|registration| registration.kind == "retained" && registration.sdk)
    {
        render_sdk_record(&mut output, retained)?;
    }
    Ok(output)
}

fn render_sdk_record(output: &mut String, registration: &Registration) -> Result<()> {
    ensure!(
        registration
            .fields
            .iter()
            .all(|field| field.role == "value"),
        "SDK value projection requires value fields: {}",
        registration.owner
    );
    let fields: Vec<_> = readable_fields(registration).collect();
    ensure!(
        !fields.is_empty(),
        "empty SDK config: {}",
        registration.owner
    );
    output.push('\n');
    for line in &registration.docs {
        writeln!(output, "/// {}", ffi_doc_line(line))?;
    }
    output.push_str("#[derive(Clone, Copy, Debug, PartialEq)]\n");
    output.push_str(
        "#[cfg_attr(\n    any(feature = \"uniffi\", feature = \"uniffi-web\"),\n    derive(uniffi::Record)\n)]\n",
    );
    output.push_str("#[cfg_attr(target_arch = \"wasm32\", wasm_bindgen::prelude::wasm_bindgen)]\n");
    writeln!(output, "pub struct Ffi{} {{", registration.owner)?;
    for field in fields {
        for line in &field.docs {
            writeln!(output, "    /// {}", ffi_doc_line(line))?;
        }
        let wire_type = ffi_type(field)?;
        ensure!(
            matches!(wire_type, "f32" | "u32" | "i32" | "bool"),
            "SDK config field {}.{} needs a scalar Web mapping",
            registration.owner,
            field.name
        );
        writeln!(output, "    pub {}: {wire_type},", field.name)?;
    }
    output.push_str("}\n");
    Ok(())
}

fn ffi_doc_line(line: &str) -> String {
    line.replace("[`", "`").replace("`]", "`")
}

fn render_record(output: &mut String, registration: &Registration) -> Result<()> {
    for line in &registration.docs {
        writeln!(output, "/// {line}")?;
    }
    output.push_str(
        "#[derive(Clone, Debug, PartialEq)]\n\
         #[cfg_attr(\n    any(feature = \"uniffi\", feature = \"uniffi-web\"),\n    derive(uniffi::Record)\n)]\n\
         pub struct FfiEqBandConfig {\n",
    );
    for field in readable_fields(registration) {
        for line in &field.docs {
            writeln!(output, "    /// {line}")?;
        }
        writeln!(output, "    pub {}: {},", field.name, ffi_type(field)?)?;
    }
    output.push_str("}\n\nimpl From<FfiEqBandConfig> for EqBandConfig {\n    fn from(value: FfiEqBandConfig) -> Self {\n        Self::builder()\n");
    for field in readable_fields(registration) {
        writeln!(
            output,
            "            .{}({})",
            field.name,
            into_domain(field, &format!("value.{}", field.name))?
        )?;
    }
    output.push_str("            .build()\n    }\n}\n");
    Ok(())
}

fn readable_fields(registration: &Registration) -> impl Iterator<Item = &RegisteredField> {
    registration
        .fields
        .iter()
        .filter(|field| field.role != "skip")
}

fn ffi_type(field: &RegisteredField) -> Result<&'static str> {
    match compact(&field.rust_type).as_str() {
        "FilterKind" => Ok("FfiEqFilterKind"),
        "GainDb" | "f32" => Ok("f32"),
        other => bail!("no FFI type mapping for {other}"),
    }
}

fn into_domain(field: &RegisteredField, value: &str) -> Result<String> {
    Ok(match compact(&field.rust_type).as_str() {
        "FilterKind" => format!(
            "match {value} {{\n                FfiEqFilterKind::LowShelf => FilterKind::LowShelf,\n                FfiEqFilterKind::Peaking => FilterKind::Peaking,\n                FfiEqFilterKind::HighShelf => FilterKind::HighShelf,\n            }}"
        ),
        "GainDb" => format!("GainDb::from({value})"),
        "f32" => value.to_owned(),
        other => bail!("no domain conversion for {other}"),
    })
}

fn compact(value: &str) -> String {
    value
        .chars()
        .filter(|character| !character.is_whitespace())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config_inventory::discover::registrations;

    #[test]
    fn projection_follows_registered_fields_and_rejects_unknown_types() {
        let source = r#"
            #[kithara_config::config]
            struct EqBandConfig {
                /// Frequency in hertz.
                #[config(value)] frequency: f32,
            }
            impl PlayerControl {
                #[kithara_config::config(delegate = "eq_layout", sdk)]
                fn set_eq_layout(&self, layout: Vec<EqBandConfig>) {}
            }
        "#;
        let registered = registrations("crates/kithara-play/src/eq.rs", source).unwrap();
        let generated = render(&registered).unwrap();
        assert!(generated.contains("pub frequency: f32"));
        assert!(generated.contains(".frequency(value.frequency)"));

        let unsupported = source.replace("frequency: f32", "frequency: Mystery");
        let registered = registrations("crates/kithara-play/src/eq.rs", &unsupported).unwrap();
        assert!(
            render(&registered)
                .unwrap_err()
                .to_string()
                .contains("Mystery")
        );
    }

    #[test]
    fn opted_in_sdk_record_uses_registered_scalar_fields() {
        let source = r#"
            /// Limiter settings.
            #[kithara_config::config(builder = false, sdk)]
            struct LimiterConfig {
                /// Output ceiling.
                #[config(value)] ceiling: f32,
                /// Release in milliseconds.
                #[config(value)] release_ms: f32,
            }
            impl PlayerControl {
                #[kithara_config::config(delegate = "eq_layout", sdk)]
                fn set_eq_layout(&self, layout: Vec<EqBandConfig>) {}
            }
            #[kithara_config::config]
            struct EqBandConfig {
                #[config(value)] frequency: f32,
            }
        "#;
        let registered = registrations("crates/kithara-play/src/eq.rs", source).unwrap();
        let generated = render(&registered).unwrap();
        assert!(generated.contains("pub struct FfiLimiterConfig"));
        assert!(generated.contains("pub release_ms: f32"));
        assert!(generated.contains("/// Release in milliseconds."));

        let unsupported = source.replace("ceiling: f32", "ceiling: FilterKind");
        let registered = registrations("crates/kithara-play/src/eq.rs", &unsupported).unwrap();
        assert!(
            render(&registered)
                .unwrap_err()
                .to_string()
                .contains("scalar Web mapping")
        );
    }
}
