use std::fmt::Write as _;

use anyhow::{Result, bail, ensure};

use super::discover::{RegisteredField, Registration};

pub(super) fn render(registrations: &[Registration]) -> Result<String> {
    let delegates: Vec<_> = registrations
        .iter()
        .filter(|registration| registration.kind == "delegate" && registration.sdk)
        .collect();
    ensure!(
        !delegates.is_empty(),
        "no SDK config operations are registered"
    );
    let mut output = String::from(
        "// @generated by `just tooling xtask config project`; do not edit.\n\
         use kithara::play::{EqBandConfig, FilterKind, GainDb};\n\n\
         /// Filter response applied by one equalizer band.\n\
         #[derive(Clone, Copy, Debug, PartialEq, Eq)]\n\
         #[cfg_attr(any(feature = \"uniffi\", feature = \"uniffi-web\"), derive(uniffi::Enum))]\n\
         pub enum FfiEqFilterKind {\n\
         \x20\x20\x20\x20LowShelf,\n\
         \x20\x20\x20\x20Peaking,\n\
         \x20\x20\x20\x20HighShelf,\n\
         }\n\n",
    );
    for delegate in delegates {
        ensure!(
            delegate.package == "kithara-play"
                && delegate.property.as_deref() == Some("eq_layout")
                && delegate.hook.as_deref() == Some("set_eq_layout"),
            "unsupported SDK config operation {}::{:?}",
            delegate.owner,
            delegate.property
        );
        ensure!(delegate.fields.len() == 1, "EQ layout requires one input");
        let input = &delegate.fields[0];
        ensure!(
            compact(&input.rust_type) == "Vec<EqBandConfig>",
            "unsupported EQ layout input {}",
            input.rust_type
        );
        let retained = registrations
            .iter()
            .find(|registration| {
                registration.kind == "retained"
                    && registration.package == "kithara-effects"
                    && registration.owner == "EqBandConfig"
            })
            .ok_or_else(|| anyhow::anyhow!("EqBandConfig is not registered"))?;
        render_record(&mut output, retained)?;
    }
    for retained in registrations
        .iter()
        .filter(|registration| registration.kind == "retained" && registration.sdk)
    {
        render_sdk_record(&mut output, retained)?;
    }
    render_source_settings(&mut output, registrations)?;
    Ok(output)
}

pub(super) fn render_host(registrations: &[Registration]) -> Result<String> {
    let exposed: Vec<_> = registrations
        .iter()
        .filter(|registration| registration.kind == "construction" && registration.sdk)
        .collect();
    ensure!(
        exposed.len() == 1,
        "expected one SDK host construction config"
    );
    let mut output = String::from(
        "// @generated by `just tooling xtask config project`; do not edit.\n\
         use super::config_generated::FfiLimiterConfig;\n",
    );
    render_host_config(&mut output, exposed[0])?;
    Ok(output)
}

fn render_host_config(output: &mut String, registration: &Registration) -> Result<()> {
    ensure!(
        registration.package == "kithara-host" && registration.owner == "HostConfig::Realtime",
        "unsupported SDK construction config {}::{}",
        registration.package,
        registration.owner
    );
    output.push_str("\n/// Settings fixed for the lifetime of the process-wide audio host.\n");
    output.push_str("#[derive(Clone, Copy, Debug, PartialEq)]\n");
    output.push_str("#[cfg_attr(\n    any(feature = \"uniffi\", feature = \"uniffi-web\"),\n    derive(uniffi::Record)\n)]\n");
    output.push_str("#[cfg_attr(target_arch = \"wasm32\", wasm_bindgen::prelude::wasm_bindgen)]\n");
    output.push_str("pub struct FfiHostConfig {\n");
    for field in readable_fields(registration) {
        for line in &field.docs {
            writeln!(output, "    /// {}", ffi_doc_line(line))?;
        }
        let wire_type = match (field.role.as_str(), compact(&field.rust_type).as_str()) {
            ("value", "NonZeroU32") => "u32",
            ("value", "Option<NonZeroU32>") => "Option<u32>",
            ("nested", "LimiterConfig") => "FfiLimiterConfig",
            _ => bail!(
                "unsupported HostConfig SDK field {}: {}",
                field.name,
                field.rust_type
            ),
        };
        writeln!(output, "    pub {}: {wire_type},", field.name)?;
    }
    output.push_str("}\n\nimpl FfiHostConfig {\n");
    output.push_str("    pub(crate) fn into_domain<S>(\n        self,\n    ) -> Result<kithara::host::HostConfig<S>, crate::types::FfiError> {\n");
    for field in readable_fields(registration) {
        let name = &field.name;
        match compact(&field.rust_type).as_str() {
            "NonZeroU32" => {
                ensure!(
                    name == "sample_rate_hint",
                    "unsupported required HostConfig field {name}"
                );
                writeln!(output, "        let {name} =")?;
                writeln!(
                    output,
                    "            std::num::NonZeroU32::new(self.{name}).ok_or_else(|| {{"
                )?;
                output.push_str("                crate::types::FfiError::InvalidArgument {\n                    reason: \"host sample rate must be greater than zero\".to_owned(),\n                }\n            })?;\n");
            }
            "Option<NonZeroU32>" => {
                ensure!(
                    name == "output_block_frames",
                    "unsupported optional HostConfig field {name}"
                );
                writeln!(output, "        let {name} = self")?;
                writeln!(output, "            .{name}")?;
                output.push_str("            .map(|frames| {\n                std::num::NonZeroU32::new(frames).ok_or_else(|| {\n                    crate::types::FfiError::InvalidArgument {\n                        reason: \"host output block size must be greater than zero\".to_owned(),\n                    }\n                })\n            })\n            .transpose()?;\n");
            }
            "LimiterConfig" => {
                ensure!(
                    name == "limiter",
                    "unsupported nested HostConfig field {name}"
                );
                writeln!(output, "        let {name} = self.{name}.try_into()?;")?;
            }
            _ => bail!(
                "unsupported HostConfig SDK conversion {}: {}",
                name,
                field.rust_type
            ),
        }
    }
    output.push_str("        Ok(kithara::host::HostConfig::builder()\n");
    for field in readable_fields(registration) {
        if compact(&field.rust_type) == "Option<NonZeroU32>" {
            writeln!(output, "            .maybe_{}({})", field.name, field.name)?;
        } else {
            writeln!(output, "            .{}({})", field.name, field.name)?;
        }
    }
    output.push_str("            .build())\n    }\n}\n");
    Ok(())
}

fn render_source_settings(output: &mut String, registrations: &[Registration]) -> Result<()> {
    let exposed: Vec<_> = registrations
        .iter()
        .filter(|registration| {
            registration
                .fields
                .iter()
                .any(|field| field.sdk_max.is_some())
        })
        .collect();
    if exposed.is_empty() {
        return Ok(());
    }
    let owners = [
        ("kithara-file", "FileConfig", "File"),
        ("kithara-hls", "HlsConfig", "Hls"),
    ];
    for (package, owner, prefix) in owners {
        let registration = exposed
            .iter()
            .find(|registration| registration.package == package && registration.owner == owner)
            .ok_or_else(|| {
                anyhow::anyhow!("missing SDK source settings owner {package}::{owner}")
            })?;
        ensure!(
            registration.kind == "construction",
            "SDK source settings owner {package}::{owner} must be a construction input"
        );
        render_source_record(output, registration, prefix)?;
    }
    ensure!(
        exposed.len() == owners.len(),
        "unsupported SDK source settings owner"
    );
    output.push_str(
        r#"
/// Per-item source settings, applied before opening the file or HLS stream.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[cfg_attr(
    any(feature = "uniffi", feature = "uniffi-web"),
    derive(uniffi::Record)
)]
pub struct FfiSourceSettings {
    /// File-stream settings, when supplied.
    pub file: Option<FfiFileSourceSettings>,
    /// HLS-stream settings, when supplied.
    pub hls: Option<FfiHlsSourceSettings>,
}
"#,
    );
    Ok(())
}

fn render_source_record(
    output: &mut String,
    registration: &Registration,
    prefix: &str,
) -> Result<()> {
    let fields: Vec<_> = registration
        .fields
        .iter()
        .filter(|field| field.sdk_max.is_some())
        .collect();
    let record = format!("Ffi{prefix}SourceSettings");
    writeln!(
        output,
        "\n/// Optional {prefix} stream settings for one item."
    )?;
    output.push_str("#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]\n");
    output.push_str("#[cfg_attr(\n    any(feature = \"uniffi\", feature = \"uniffi-web\"),\n    derive(uniffi::Record)\n)]\n");
    writeln!(output, "pub struct {record} {{")?;
    for field in &fields {
        ensure!(
            field.role == "value" && compact(&field.rust_type) == "usize" && !field.docs.is_empty(),
            "SDK source field {}.{} needs a documented usize value",
            registration.owner,
            field.name
        );
        for line in &field.docs {
            writeln!(output, "    /// {}", ffi_doc_line(line))?;
        }
        writeln!(
            output,
            "    /// Accepted range: 1..={}.",
            field.sdk_max.unwrap_or_default()
        )?;
        writeln!(output, "    pub {}: Option<u32>,", field.name)?;
    }
    output.push_str("}\n");
    writeln!(
        output,
        "\nimpl TryFrom<{record}> for kithara_{}::{}Patch {{",
        if prefix == "File" { "file" } else { "hls" },
        registration.owner
    )?;
    output.push_str("    type Error = crate::types::FfiError;\n\n");
    writeln!(
        output,
        "    fn try_from(value: {record}) -> Result<Self, Self::Error> {{"
    )?;
    output.push_str("        let mut patch = Self::default();\n");
    for field in fields {
        let maximum = field.sdk_max.unwrap_or_default();
        writeln!(
            output,
            "        if let Some(input) = value.{} {{",
            field.name
        )?;
        writeln!(output, "            if input == 0 || input > {maximum} {{")?;
        output.push_str("                return Err(crate::types::FfiError::InvalidArgument {\n");
        writeln!(
            output,
            "                    reason: \"{}.{} must be in 1..={maximum}\".into(),",
            registration.owner, field.name
        )?;
        output.push_str("                });\n            }\n");
        writeln!(
            output,
            "            patch.{} = Some(input as usize);",
            field.name
        )?;
        output.push_str("        }\n");
    }
    output.push_str("        Ok(patch)\n    }\n}\n");
    Ok(())
}

fn render_sdk_record(output: &mut String, registration: &Registration) -> Result<()> {
    ensure!(
        registration
            .fields
            .iter()
            .all(|field| field.role == "value"),
        "SDK value projection requires value fields: {}",
        registration.owner
    );
    let fields: Vec<_> = readable_fields(registration).collect();
    ensure!(
        !fields.is_empty(),
        "empty SDK config: {}",
        registration.owner
    );
    if registration.owner == "CrossfadeSettings" {
        ensure!(
            registration.package == "kithara-play"
                && fields
                    .iter()
                    .map(|field| field.name.as_str())
                    .collect::<Vec<_>>()
                    == ["duration", "curve", "depth", "position"]
                && fields
                    .iter()
                    .map(|field| compact(&field.rust_type))
                    .collect::<Vec<_>>()
                    == ["f32", "CrossfadeCurve", "f32", "f32"],
            "CrossfadeSettings SDK conversion requires duration: f32, curve: CrossfadeCurve, depth: f32, position: f32"
        );
    }
    output.push('\n');
    for line in &registration.docs {
        writeln!(output, "/// {}", ffi_doc_line(line))?;
    }
    output.push_str("#[derive(Clone, Copy, Debug, PartialEq)]\n");
    output.push_str(
        "#[cfg_attr(\n    any(feature = \"uniffi\", feature = \"uniffi-web\"),\n    derive(uniffi::Record)\n)]\n",
    );
    if registration.owner != "CrossfadeSettings" {
        output.push_str(
            "#[cfg_attr(target_arch = \"wasm32\", wasm_bindgen::prelude::wasm_bindgen)]\n",
        );
    }
    writeln!(output, "pub struct Ffi{} {{", registration.owner)?;
    for field in &fields {
        for line in &field.docs {
            writeln!(output, "    /// {}", ffi_doc_line(line))?;
        }
        let wire_type = ffi_type(field)?;
        ensure!(
            matches!(wire_type, "f32" | "u32" | "i32" | "bool")
                || registration.owner == "CrossfadeSettings"
                    && wire_type == "crate::types::FfiCrossfadeCurve",
            "SDK config field {}.{} needs a scalar Web mapping",
            registration.owner,
            field.name
        );
        writeln!(output, "    pub {}: {wire_type},", field.name)?;
    }
    output.push_str("}\n");
    if registration.owner == "CrossfadeSettings" {
        output.push_str("\nimpl From<kithara::play::CrossfadeSettings> for FfiCrossfadeSettings {\n    fn from(value: kithara::play::CrossfadeSettings) -> Self {\n        let values = kithara_config::Config::values(&value);\n        Self {\n            duration: values.duration,\n            curve: match values.curve {\n                kithara::play::CrossfadeCurve::Linear => crate::types::FfiCrossfadeCurve::Linear,\n                kithara::play::CrossfadeCurve::EqualPower => {\n                    crate::types::FfiCrossfadeCurve::EqualPower\n                }\n                _ => crate::types::FfiCrossfadeCurve::Unknown,\n            },\n            depth: values.depth,\n            position: values.position,\n        }\n    }\n}\n\nimpl TryFrom<FfiCrossfadeSettings> for kithara::play::CrossfadeSettings {\n    type Error = crate::types::FfiError;\n\n    fn try_from(value: FfiCrossfadeSettings) -> Result<Self, Self::Error> {\n        let curve = match value.curve {\n            crate::types::FfiCrossfadeCurve::Linear => kithara::play::CrossfadeCurve::Linear,\n            crate::types::FfiCrossfadeCurve::EqualPower => {\n                kithara::play::CrossfadeCurve::EqualPower\n            }\n            crate::types::FfiCrossfadeCurve::Unknown => {\n                return Err(crate::types::FfiError::InvalidArgument {\n                    reason: \"unknown crossfade curve\".into(),\n                });\n            }\n        };\n        Self::new(value.duration, curve, value.depth, value.position)\n            .map_err(crate::types::FfiError::from)\n    }\n}\n");
    }
    if registration.package == "kithara-effects" && registration.owner == "LimiterConfig" {
        output.push_str("\nimpl Default for FfiLimiterConfig {\n    fn default() -> Self {\n        let config = kithara::effects::LimiterConfig::default();\n        Self {\n");
        for field in &fields {
            writeln!(
                output,
                "            {}: config.{}(),",
                field.name, field.name
            )?;
        }
        output.push_str("        }\n    }\n}\n\nimpl TryFrom<FfiLimiterConfig> for kithara::effects::LimiterConfig {\n    type Error = crate::types::FfiError;\n\n    fn try_from(config: FfiLimiterConfig) -> Result<Self, Self::Error> {\n        Self::builder()\n");
        for field in &fields {
            writeln!(output, "            .{}(config.{})", field.name, field.name)?;
        }
        output.push_str("            .build()\n            .map_err(|error| crate::types::FfiError::InvalidArgument {\n                reason: error.to_string(),\n            })\n    }\n}\n");
    }
    Ok(())
}

fn ffi_doc_line(line: &str) -> String {
    line.replace("[`", "`").replace("`]", "`")
}

fn render_record(output: &mut String, registration: &Registration) -> Result<()> {
    for line in &registration.docs {
        writeln!(output, "/// {line}")?;
    }
    output.push_str(
        "#[derive(Clone, Debug, PartialEq)]\n\
         #[cfg_attr(\n    any(feature = \"uniffi\", feature = \"uniffi-web\"),\n    derive(uniffi::Record)\n)]\n\
         pub struct FfiEqBandConfig {\n",
    );
    for field in readable_fields(registration) {
        for line in &field.docs {
            writeln!(output, "    /// {line}")?;
        }
        writeln!(output, "    pub {}: {},", field.name, ffi_type(field)?)?;
    }
    output.push_str("}\n\nimpl From<FfiEqBandConfig> for EqBandConfig {\n    fn from(value: FfiEqBandConfig) -> Self {\n        Self::builder()\n");
    for field in readable_fields(registration) {
        writeln!(
            output,
            "            .{}({})",
            field.name,
            into_domain(field, &format!("value.{}", field.name))?
        )?;
    }
    output.push_str("            .build()\n    }\n}\n");
    Ok(())
}

fn readable_fields(registration: &Registration) -> impl Iterator<Item = &RegisteredField> {
    registration
        .fields
        .iter()
        .filter(|field| field.role != "skip")
}

fn ffi_type(field: &RegisteredField) -> Result<&'static str> {
    match compact(&field.rust_type).as_str() {
        "FilterKind" => Ok("FfiEqFilterKind"),
        "GainDb" | "f32" => Ok("f32"),
        "CrossfadeCurve" => Ok("crate::types::FfiCrossfadeCurve"),
        other => bail!("no FFI type mapping for {other}"),
    }
}

fn into_domain(field: &RegisteredField, value: &str) -> Result<String> {
    Ok(match compact(&field.rust_type).as_str() {
        "FilterKind" => format!(
            "match {value} {{\n                FfiEqFilterKind::LowShelf => FilterKind::LowShelf,\n                FfiEqFilterKind::Peaking => FilterKind::Peaking,\n                FfiEqFilterKind::HighShelf => FilterKind::HighShelf,\n            }}"
        ),
        "GainDb" => format!("GainDb::from({value})"),
        "f32" => value.to_owned(),
        other => bail!("no domain conversion for {other}"),
    })
}

fn compact(value: &str) -> String {
    value
        .chars()
        .filter(|character| !character.is_whitespace())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config_inventory::discover::registrations;

    #[test]
    fn host_record_follows_realtime_registration_and_rejects_unknown_fields() {
        let host = r#"
            #[kithara_config::config(construction, builder = false)]
            enum HostConfig<S> {
                #[config(sdk)]
                Realtime {
                    /// Initial device rate.
                    #[config(value)] sample_rate_hint: NonZeroU32,
                    /// Optional callback block size.
                    #[config(value)] output_block_frames: Option<NonZeroU32>,
                    /// Limiter policy.
                    #[config(nested)] limiter: LimiterConfig,
                    #[config(skip = "type marker")] marker: PhantomData<S>,
                }
            }
        "#;
        let limiter = r#"
            #[kithara_config::config(builder = false, sdk)]
            struct LimiterConfig {
                #[config(value)] ceiling: f32,
                #[config(value)] release_ms: f32,
            }
            #[kithara_config::config]
            struct EqBandConfig {
                #[config(value)] frequency: f32,
            }
        "#;
        let delegate = r#"
            impl PlayerControl {
                #[kithara_config::config(delegate = "eq_layout", sdk)]
                fn set_eq_layout(&self, layout: Vec<EqBandConfig>) {}
            }
        "#;
        let mut registered = registrations("crates/kithara-host/src/host/config.rs", host).unwrap();
        registered.extend(registrations("crates/kithara-effects/src/eq.rs", limiter).unwrap());
        registered.extend(registrations("crates/kithara-play/src/player.rs", delegate).unwrap());
        let generated = render_host(&registered).unwrap();
        assert!(generated.contains("pub struct FfiHostConfig"));
        assert!(generated.contains("pub output_block_frames: Option<u32>"));
        assert!(generated.contains(".maybe_output_block_frames(output_block_frames)"));
        assert!(generated.contains("/// Initial device rate."));

        let unsupported = host.replace(
            "#[config(nested)] limiter: LimiterConfig,",
            "#[config(nested)] limiter: LimiterConfig, #[config(value)] mystery: String,",
        );
        let mut registered =
            registrations("crates/kithara-host/src/host/config.rs", &unsupported).unwrap();
        registered.extend(registrations("crates/kithara-effects/src/eq.rs", limiter).unwrap());
        registered.extend(registrations("crates/kithara-play/src/player.rs", delegate).unwrap());
        assert!(
            render_host(&registered)
                .unwrap_err()
                .to_string()
                .contains("mystery")
        );
    }

    #[test]
    fn projection_follows_registered_fields_and_rejects_unknown_types() {
        let source = r#"
            #[kithara_config::config]
            struct EqBandConfig {
                /// Frequency in hertz.
                #[config(value)] frequency: f32,
            }
        "#;
        let delegate = r#"
            impl PlayerControl {
                #[kithara_config::config(delegate = "eq_layout", sdk)]
                fn set_eq_layout(&self, layout: Vec<EqBandConfig>) {}
            }
        "#;
        let mut registered =
            registrations("crates/kithara-effects/src/eq/band.rs", source).unwrap();
        registered.extend(registrations("crates/kithara-play/src/player.rs", delegate).unwrap());
        let generated = render(&registered).unwrap();
        assert!(generated.contains("pub frequency: f32"));
        assert!(generated.contains(".frequency(value.frequency)"));

        let unsupported = source.replace("frequency: f32", "frequency: Mystery");
        let mut registered =
            registrations("crates/kithara-effects/src/eq/band.rs", &unsupported).unwrap();
        registered.extend(registrations("crates/kithara-play/src/player.rs", delegate).unwrap());
        assert!(
            render(&registered)
                .unwrap_err()
                .to_string()
                .contains("Mystery")
        );
    }

    #[test]
    fn opted_in_sdk_record_uses_registered_scalar_fields() {
        let source = r#"
            /// Limiter settings.
            #[kithara_config::config(builder = false, sdk)]
            struct LimiterConfig {
                /// Output ceiling.
                #[config(value)] ceiling: f32,
                /// Release in milliseconds.
                #[config(value)] release_ms: f32,
            }
            #[kithara_config::config]
            struct EqBandConfig {
                #[config(value)] frequency: f32,
            }
        "#;
        let delegate = r#"
            impl PlayerControl {
                #[kithara_config::config(delegate = "eq_layout", sdk)]
                fn set_eq_layout(&self, layout: Vec<EqBandConfig>) {}
            }
        "#;
        let mut registered = registrations("crates/kithara-effects/src/eq.rs", source).unwrap();
        registered.extend(registrations("crates/kithara-play/src/player.rs", delegate).unwrap());
        let generated = render(&registered).unwrap();
        assert!(generated.contains("pub struct FfiLimiterConfig"));
        assert!(generated.contains("pub release_ms: f32"));
        assert!(generated.contains("/// Release in milliseconds."));
        assert!(generated.contains("release_ms: config.release_ms()"));
        assert!(generated.contains(".release_ms(config.release_ms)"));

        let unsupported = source.replace("ceiling: f32", "ceiling: FilterKind");
        let mut registered =
            registrations("crates/kithara-effects/src/eq.rs", &unsupported).unwrap();
        registered.extend(registrations("crates/kithara-play/src/player.rs", delegate).unwrap());
        assert!(
            render(&registered)
                .unwrap_err()
                .to_string()
                .contains("scalar Web mapping")
        );
    }

    #[test]
    fn crossfade_projection_rejects_unmapped_fields() {
        let source = r#"
            #[kithara_config::config(builder = false, sdk)]
            struct CrossfadeSettings {
                #[config(value)] duration: f32,
                #[config(value)] curve: CrossfadeCurve,
                #[config(value)] depth: f32,
                #[config(value)] position: f32,
            }
            impl PlayerControl {
                #[kithara_config::config(delegate = "eq_layout", sdk)]
                fn set_eq_layout(&self, layout: Vec<EqBandConfig>) {}
            }
        "#;
        let band =
            "#[kithara_config::config] struct EqBandConfig { #[config(value)] frequency: f32 }";
        let mut registered =
            registrations("crates/kithara-play/src/api/crossfade.rs", source).unwrap();
        registered.extend(registrations("crates/kithara-effects/src/eq/band.rs", band).unwrap());
        let generated = render(&registered).unwrap();
        assert!(generated.contains("let values = kithara_config::Config::values(&value)"));
        assert!(
            generated.contains("Self::new(value.duration, curve, value.depth, value.position)")
        );

        let extra = source.replace(
            "#[config(value)] position: f32,",
            "#[config(value)] position: f32, #[config(value)] offset: f32,",
        );
        let mut registered =
            registrations("crates/kithara-play/src/api/crossfade.rs", &extra).unwrap();
        registered.extend(registrations("crates/kithara-effects/src/eq/band.rs", band).unwrap());
        assert!(
            render(&registered)
                .unwrap_err()
                .to_string()
                .contains("CrossfadeSettings SDK conversion requires")
        );
    }

    #[test]
    fn source_projection_follows_owner_fields_and_limits() {
        let mut registered = registrations(
            "crates/kithara-effects/src/eq/band.rs",
            "#[kithara_config::config] struct EqBandConfig { #[config(value)] frequency: f32 }",
        )
        .unwrap();
        registered.extend(
            registrations(
                "crates/kithara-play/src/player.rs",
                "impl PlayerControl { #[kithara_config::config(delegate = \"eq_layout\", sdk)] fn set_eq_layout(&self, layout: Vec<EqBandConfig>) {} }",
            )
            .unwrap(),
        );
        for (path, owner, field, max) in [
            (
                "crates/kithara-file/src/config.rs",
                "FileConfig",
                "reader_event_capacity",
                4096,
            ),
            (
                "crates/kithara-hls/src/config.rs",
                "HlsConfig",
                "download_batch_size",
                64,
            ),
        ] {
            registered.extend(
                registrations(
                    path,
                    &format!(
                        "#[kithara_config::config(construction)] struct {owner} {{ /// Capacity.\n #[config(value, sdk(max = {max}))] {field}: usize }}"
                    ),
                )
                .unwrap(),
            );
        }
        let generated = render(&registered).unwrap();
        assert!(generated.contains("pub reader_event_capacity: Option<u32>"));
        assert!(generated.contains("pub download_batch_size: Option<u32>"));
        assert!(generated.contains("input > 4096"));
        assert!(generated.contains("input > 64"));
        assert!(generated.contains("patch.reader_event_capacity = Some(input as usize)"));
        assert!(generated.contains("patch.download_batch_size = Some(input as usize)"));

        let unsupported = registered
            .iter_mut()
            .find(|registration| registration.owner == "FileConfig")
            .unwrap();
        unsupported.fields[0].rust_type = "String".into();
        assert!(render(&registered).is_err());
    }
}
