//! Materializes every registered asset into the shared store and writes one
//! accessor per case into `OUT_DIR`.
//!
//! `src/defs/` and `src/registry.rs` compile only here — the library never sees
//! them, which is what keeps encoding itself out of the target build.
//! `src/signal/` and `src/store.rs` are shared: the same sources, reached from
//! two roots.

#[path = "src/defs/mod.rs"]
mod defs;
#[path = "src/encoder_crates.rs"]
mod encoder_crates;
#[path = "src/registry.rs"]
mod registry;
// `signal` and `store` keep the visibility they have in the library: the same
// source files, reached from two roots.
#[path = "src/signal/mod.rs"]
pub mod signal;
#[path = "src/store.rs"]
pub mod store;

use std::{
    collections::{HashSet, hash_map::DefaultHasher},
    fmt::Write as _,
    fs,
    hash::{Hash, Hasher},
    path::{Path, PathBuf},
};

use encoder_crates::Lockfile;
use registry::AssetDef;

/// Source trees whose contents decide the generated bytes.
const HASHED_TREES: [&str; 3] = ["src/defs", "src/signal", "../kithara-encode/src"];
/// Individual sources outside those trees that decide the same.
const HASHED_FILES: [&str; 4] = [
    "build.rs",
    "src/encoder_crates.rs",
    "src/registry.rs",
    "src/store.rs",
];

/// The workspace lockfile, read for the resolved encoder versions.
const LOCKFILE: &str = "../../Cargo.lock";

fn hash_rs_tree(dir: &Path, hasher: &mut DefaultHasher) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    let mut paths: Vec<_> = entries.flatten().map(|entry| entry.path()).collect();
    paths.sort();
    for path in paths {
        if path.is_dir() {
            hash_rs_tree(&path, hasher);
        } else if path.extension().is_some_and(|ext| ext == "rs") {
            if let Ok(bytes) = fs::read(&path) {
                path.to_string_lossy().hash(hasher);
                bytes.hash(hasher);
            }
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }
}

fn hash_encoder_versions(hasher: &mut DefaultHasher) {
    println!("cargo:rerun-if-changed={LOCKFILE}");
    let text = fs::read_to_string(LOCKFILE).expect("the workspace lockfile must be readable");
    let lockfile = Lockfile::parse(&text).unwrap_or_else(|error| panic!("{LOCKFILE}: {error}"));

    // The list this hashes is hand-written, so it is guarded from both sides:
    // `encoder_versions` fails when a listed crate stops resolving, and an
    // unclassified new dependency of `kithara-encode` fails here — its version
    // would otherwise never reach the fingerprint, leaving the store free to
    // serve bytes the previous encoder produced.
    let unclassified = lockfile
        .unclassified_encode_dependencies()
        .unwrap_or_else(|error| panic!("{LOCKFILE}: {error}"));
    assert!(
        unclassified.is_empty(),
        "{LOCKFILE}: unclassified kithara-encode dependencies: {unclassified:?}; add each crate \
         to ENCODERS if it can change an encoded byte, otherwise to NON_ENCODING_DEPENDENCIES"
    );

    let resolved = lockfile
        .encoder_versions()
        .unwrap_or_else(|error| panic!("{LOCKFILE}: {error}"));
    resolved.hash(hasher);
}

fn fingerprint() -> String {
    let mut hasher = DefaultHasher::new();
    for dir in HASHED_TREES {
        println!("cargo:rerun-if-changed={dir}");
        hash_rs_tree(Path::new(dir), &mut hasher);
    }
    for file in HASHED_FILES {
        fs::read(file)
            .unwrap_or_else(|error| panic!("kithara-test-fixtures: cannot read {file}: {error}"))
            .hash(&mut hasher);
        println!("cargo:rerun-if-changed={file}");
    }
    hash_encoder_versions(&mut hasher);
    let hex = format!("{:016x}", hasher.finish());
    assert_eq!(
        hex.len(),
        store::FINGERPRINT_HEX_LEN,
        "kithara-test-fixtures: the namespace length the store publishes must match what this writes",
    );
    hex
}

/// Rejects two cases that would produce one accessor, before either is written.
fn resolve(defs: &[&'static AssetDef]) -> Vec<(String, String, &'static AssetDef)> {
    let mut seen: HashSet<String> = HashSet::new();
    let mut resolved = Vec::with_capacity(defs.len());
    for def in defs {
        let name = def.accessor_name();
        assert!(
            seen.insert(name.clone()),
            "kithara-test-fixtures: two asset cases share the accessor name `{name}`",
        );
        let id = store::asset_id(def.func, def.case);
        resolved.push((name, id, *def));
    }
    resolved
}

fn materialize(namespace: &Path, resolved: &[(String, String, &'static AssetDef)]) {
    for (name, id, def) in resolved {
        if store::read_entry(namespace, id, def.ext).is_some() {
            continue;
        }
        let _lock = store::lock_entry(namespace, id)
            .unwrap_or_else(|error| panic!("kithara-test-fixtures: lock for `{name}`: {error}"));
        if store::read_entry(namespace, id, def.ext).is_some() {
            continue;
        }
        let bytes = (def.build)();
        assert!(
            !bytes.is_empty(),
            "kithara-test-fixtures: `{name}` produced no bytes"
        );
        store::write_entry(namespace, id, def.ext, &bytes)
            .unwrap_or_else(|error| panic!("kithara-test-fixtures: write `{name}`: {error}"));
    }
}

fn codegen(namespace: &Path, resolved: &[(String, String, &'static AssetDef)]) -> String {
    let mut out = String::new();
    let mut manifest = String::new();
    let mut by_name = String::new();
    for (name, id, def) in resolved {
        let entry = format!("ENTRY_{}", name.to_uppercase());
        let path = store::entry_path(namespace, id, def.ext);
        let path = path.to_str().unwrap_or_else(|| {
            panic!("kithara-test-fixtures: the store path for `{name}` is not valid UTF-8")
        });
        let content_type = def.content_type;
        // rustc records an `include_bytes!` path in dep-info, so cargo tracks
        // the store entry an embedded accessor was built from. An on-disk
        // accessor reads the file at run time, which wasm has no way to do.
        let (cfg, body) = if def.embed {
            (
                "",
                format!("    crate::asset::Asset::embedded(&{entry}, include_bytes!({path:?}))"),
            )
        } else {
            (
                "#[cfg(not(target_arch = \"wasm32\"))]\n",
                format!(
                    "    static BYTES: ::std::sync::OnceLock<Vec<u8>> = \
                     ::std::sync::OnceLock::new();\n    \
                     crate::asset::Asset::on_disk(&{entry}, &BYTES)"
                ),
            )
        };
        let _ = write!(
            out,
            "static {entry}: crate::asset::AssetEntry = crate::asset::AssetEntry {{\n    \
             name: {name:?},\n    id: {id:?},\n    path: {path:?},\n    \
             content_type: {content_type:?},\n}};\n\n\
             {cfg}#[must_use]\n\
             pub fn {name}() -> crate::asset::Asset {{\n{body}\n}}\n\n",
        );
        let _ = writeln!(manifest, "    &{entry},");
        let _ = writeln!(
            by_name,
            "        {}{name:?} => Some({name}()),",
            cfg.replace('\n', "\n        "),
        );
    }
    let _ = write!(
        out,
        "/// Every asset this build materialized.\n\
         pub static MANIFEST: &[&crate::asset::AssetEntry] = &[\n{manifest}];\n\n\
         /// The asset this build registered under `name`.\n\
         #[must_use]\n\
         pub fn by_name(name: &str) -> Option<crate::asset::Asset> {{\n    \
         match name {{\n{by_name}        _ => None,\n    }}\n}}\n",
    );
    out
}

fn main() {
    println!("cargo:rerun-if-env-changed={}", store::STORE_ENV);

    let defs: Vec<&AssetDef> = inventory::iter::<AssetDef>.into_iter().collect();
    assert!(
        !defs.is_empty(),
        "kithara-test-fixtures: the asset registry is empty; either `src/defs` declares no \
         `#[kithara::asset]`, or the registrations were dropped at link time",
    );
    let resolved = resolve(&defs);

    let fingerprint = fingerprint();
    let namespace = store::namespace(&store::root_from_env(), &fingerprint);
    materialize(&namespace, &resolved);

    // Written once per namespace so its mtime stays put on a no-op rerun; a
    // wiped store makes the declared path missing, which cargo reads as
    // changed and reruns this script.
    let stamp = namespace.join(".stamp");
    if fs::read(&stamp).ok().as_deref() != Some(fingerprint.as_bytes()) {
        fs::write(&stamp, fingerprint.as_bytes())
            .unwrap_or_else(|error| panic!("kithara-test-fixtures: write stamp: {error}"));
    }
    println!("cargo:rerun-if-changed={}", stamp.display());

    let out_dir =
        PathBuf::from(std::env::var_os("OUT_DIR").expect("invariant: cargo always sets OUT_DIR"));
    fs::write(out_dir.join("assets.rs"), codegen(&namespace, &resolved))
        .unwrap_or_else(|error| panic!("kithara-test-fixtures: write assets.rs: {error}"));
}
