//! Materializes every registered asset into the shared store and writes one
//! accessor per case into `OUT_DIR`.
//!
//! `src/defs/` and `src/registry.rs` compile only here — the library never sees
//! them, which is what keeps encoding itself out of the target build.
//! `src/signal/` and `src/store.rs` are shared: the same sources, reached from
//! two roots.

#[path = "src/context.rs"]
mod context;
#[path = "src/defs/mod.rs"]
mod defs;
#[path = "src/encoders.rs"]
mod encoders;
#[path = "src/registry.rs"]
mod registry;
// `fmp4`, `signal`, and `store` keep the visibility they have in the library:
// the same source files, reached from two roots.
#[path = "src/fmp4/mod.rs"]
pub mod fmp4;
#[path = "src/graph.rs"]
mod graph;
#[path = "src/hls/hydrate.rs"]
mod hls_hydrate;
#[path = "src/hls/manifest.rs"]
mod hls_manifest;
#[path = "src/signal/mod.rs"]
pub mod signal;
#[path = "src/store.rs"]
pub mod store;

use std::{
    collections::{HashMap, HashSet, hash_map::DefaultHasher},
    fmt::Write as _,
    fs,
    hash::{Hash, Hasher},
    panic::resume_unwind,
    path::{Path, PathBuf},
    thread,
};

use encoders::Lockfile;
use registry::{AssetBuild, AssetDef};

const REMOTE_FIXTURES_ENV: &str = "KITHARA_REMOTE_FIXTURES";

/// Source trees whose contents decide the generated bytes.
const HASHED_TREES: [&str; 5] = [
    "src/defs",
    "src/fmp4",
    "src/hls",
    "src/signal",
    "../kithara-encode/src",
];
/// Individual sources outside those trees that decide the same.
const HASHED_FILES: [&str; 4] = [
    "build.rs",
    "src/encoders.rs",
    "src/registry.rs",
    "src/store.rs",
];

/// The workspace lockfile, read for the resolved encoder versions.
const LOCKFILE: &str = "../../Cargo.lock";

fn hash_rs_tree(dir: &Path, hasher: &mut DefaultHasher) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    let mut paths: Vec<_> = entries.flatten().map(|entry| entry.path()).collect();
    paths.sort();
    for path in paths {
        if path.is_dir() {
            hash_rs_tree(&path, hasher);
        } else if path.extension().is_some_and(|ext| ext == "rs") {
            if let Ok(bytes) = fs::read(&path) {
                path.to_string_lossy().hash(hasher);
                bytes.hash(hasher);
            }
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }
}

fn hash_encoder_versions(hasher: &mut DefaultHasher) {
    println!("cargo:rerun-if-changed={LOCKFILE}");
    let text = fs::read_to_string(LOCKFILE).expect("the workspace lockfile must be readable");
    let lockfile = Lockfile::parse(&text).unwrap_or_else(|error| panic!("{LOCKFILE}: {error}"));

    // The list this hashes is hand-written, so it is guarded from both sides:
    // `encoder_versions` fails when a listed crate stops resolving, and an
    // unclassified new dependency of `kithara-encode` fails here — its version
    // would otherwise never reach the fingerprint, leaving the store free to
    // serve bytes the previous encoder produced.
    let unclassified = lockfile
        .unclassified_encode_dependencies()
        .unwrap_or_else(|error| panic!("{LOCKFILE}: {error}"));
    assert!(
        unclassified.is_empty(),
        "{LOCKFILE}: unclassified kithara-encode dependencies: {unclassified:?}; add each crate \
         to ENCODERS if it can change an encoded byte, otherwise to NON_ENCODING_DEPENDENCIES"
    );

    let resolved = lockfile
        .encoder_versions()
        .unwrap_or_else(|error| panic!("{LOCKFILE}: {error}"));
    resolved.hash(hasher);
}

fn fingerprint() -> String {
    let mut hasher = DefaultHasher::new();
    for dir in HASHED_TREES {
        println!("cargo:rerun-if-changed={dir}");
        hash_rs_tree(Path::new(dir), &mut hasher);
    }
    for file in HASHED_FILES {
        fs::read(file)
            .unwrap_or_else(|error| panic!("kithara-test-fixtures: cannot read {file}: {error}"))
            .hash(&mut hasher);
        println!("cargo:rerun-if-changed={file}");
    }
    hash_encoder_versions(&mut hasher);
    let hex = format!("{:016x}", hasher.finish());
    assert_eq!(
        hex.len(),
        store::FINGERPRINT_HEX_LEN,
        "kithara-test-fixtures: the namespace length the store publishes must match what this writes",
    );
    hex
}

/// Rejects two cases that would produce one accessor, before either is written.
fn resolve(defs: &[&'static AssetDef]) -> Vec<(String, String, &'static AssetDef)> {
    let mut seen: HashSet<String> = HashSet::new();
    let mut resolved = Vec::with_capacity(defs.len());
    for def in defs {
        let name = def.accessor_name();
        assert!(
            seen.insert(name.clone()),
            "kithara-test-fixtures: two asset cases share the accessor name `{name}`",
        );
        let id = store::asset_id(def.func, def.case);
        resolved.push((name, id, *def));
    }
    resolved
}

fn materialize(
    namespace: &Path,
    resolved: &[(String, String, &'static AssetDef)],
) -> HashMap<String, String> {
    let mut unavailable = HashMap::new();
    let nodes: Vec<_> = resolved
        .iter()
        .map(|(name, _, def)| graph::Node {
            name,
            dependencies: def.dependencies,
        })
        .collect();
    let levels =
        graph::levels(&nodes).unwrap_or_else(|error| panic!("kithara-test-fixtures: {error}"));
    let parallelism = thread::available_parallelism().map_or(1, usize::from);

    for level in levels {
        for batch in level.chunks(parallelism) {
            let results = thread::scope(|scope| {
                batch
                    .iter()
                    .map(|&index| scope.spawn(move || materialize_one(namespace, resolved, index)))
                    .collect::<Vec<_>>()
                    .into_iter()
                    .map(|handle| handle.join().unwrap_or_else(|panic| resume_unwind(panic)))
                    .collect::<Vec<_>>()
            });
            unavailable.extend(results.into_iter().flatten());
        }
    }
    unavailable
}

fn materialize_one(
    namespace: &Path,
    resolved: &[(String, String, &'static AssetDef)],
    index: usize,
) -> Option<(String, String)> {
    let (name, id, def) = &resolved[index];
    if store::has_entry(namespace, id, def.ext) {
        return None;
    }
    if def.optional && std::env::var_os(REMOTE_FIXTURES_ENV).is_none() {
        return Some((
            name.clone(),
            format!("remote hydration disabled; set {REMOTE_FIXTURES_ENV}"),
        ));
    }
    let _lock = store::lock_entry(namespace, id)
        .unwrap_or_else(|error| panic!("kithara-test-fixtures: lock for `{name}`: {error}"));
    if store::has_entry(namespace, id, def.ext) {
        return None;
    }
    let dependency_bytes: Vec<_> = def
        .dependencies
        .iter()
        .map(|dependency| {
            let (_, dependency_id, dependency_def) = resolved
                .iter()
                .find(|(candidate, _, _)| candidate == dependency)
                .unwrap_or_else(|| {
                    panic!(
                        "kithara-test-fixtures: graph accepted missing dependency `{dependency}`"
                    )
                });
            store::read_entry(namespace, dependency_id, dependency_def.ext).unwrap_or_else(|| {
                panic!(
                    "kithara-test-fixtures: dependency `{dependency}` of `{name}` was not materialized"
                )
            })
        })
        .collect();
    let inputs: Vec<_> = dependency_bytes.iter().map(Vec::as_slice).collect();
    let context = context::BuildContext::new(namespace, id);
    let bytes = match (def.build)(context, &inputs) {
        AssetBuild::Ready(bytes) => bytes,
        AssetBuild::Unavailable(reason) if def.optional => {
            println!("cargo:warning=optional fixture `{name}` unavailable: {reason}");
            println!(
                "cargo:rerun-if-changed={}",
                store::entry_path(namespace, id, def.ext).display()
            );
            return Some((name.clone(), reason));
        }
        AssetBuild::Unavailable(reason) => {
            panic!("kithara-test-fixtures: required fixture `{name}` unavailable: {reason}")
        }
    };
    assert!(
        !bytes.is_empty(),
        "kithara-test-fixtures: `{name}` produced no bytes"
    );
    store::write_entry(namespace, id, def.ext, &bytes)
        .unwrap_or_else(|error| panic!("kithara-test-fixtures: write `{name}`: {error}"));
    None
}

fn codegen(
    namespace: &Path,
    resolved: &[(String, String, &'static AssetDef)],
    unavailable: &HashMap<String, String>,
) -> String {
    let mut out = String::new();
    let mut manifest = String::new();
    let mut by_name = String::new();
    for (name, id, def) in resolved {
        let entry = format!("ENTRY_{}", name.to_uppercase());
        let path = store::entry_path(namespace, id, def.ext);
        let path = path.to_str().unwrap_or_else(|| {
            panic!("kithara-test-fixtures: the store path for `{name}` is not valid UTF-8")
        });
        let content_type = def.content_type;
        let unavailable = unavailable
            .get(name)
            .map_or_else(|| "None".to_owned(), |reason| format!("Some({reason:?})"));
        // rustc records an `include_bytes!` path in dep-info, so cargo tracks
        // the store entry an embedded accessor was built from. An on-disk
        // accessor reads the file at run time, which wasm has no way to do.
        let (cfg, body) = if def.embed {
            (
                "",
                format!("    crate::asset::Asset::embedded(&{entry}, include_bytes!({path:?}))"),
            )
        } else {
            (
                "#[cfg(not(target_arch = \"wasm32\"))]\n",
                format!(
                    "    static BYTES: ::std::sync::OnceLock<Vec<u8>> = \
                     ::std::sync::OnceLock::new();\n    \
                     crate::asset::Asset::on_disk(&{entry}, &BYTES)"
                ),
            )
        };
        let _ = write!(
            out,
            "static {entry}: crate::asset::AssetEntry = crate::asset::AssetEntry {{\n    \
             name: {name:?},\n    id: {id:?},\n    path: {path:?},\n    \
             content_type: {content_type:?},\n    unavailable: {unavailable},\n}};\n\n\
             {cfg}#[must_use]\n\
             pub fn {name}() -> crate::asset::Asset {{\n{body}\n}}\n\n",
        );
        let _ = writeln!(manifest, "    &{entry},");
        let _ = writeln!(
            by_name,
            "    {}({name:?}, {name}),",
            cfg.replace('\n', "\n        "),
        );
    }
    let _ = write!(
        out,
        "/// Every asset this build materialized.\n\
         pub static MANIFEST: &[&crate::asset::AssetEntry] = &[\n{manifest}];\n\n\
         type AssetLookup = (&'static str, fn() -> crate::asset::Asset);\n\n\
         static BY_NAME: &[AssetLookup] = &[\n{by_name}];\n\n\
         /// The asset this build registered under `name`.\n\
         #[must_use]\n\
         pub fn by_name(name: &str) -> Option<crate::asset::Asset> {{\n    \
         BY_NAME\n        .iter()\n        .find(|(candidate, _)| *candidate == name)\n        \
         .map(|(_, asset)| asset())\n}}\n",
    );
    out
}

fn main() {
    println!("cargo:rerun-if-env-changed={}", store::STORE_ENV);
    println!("cargo:rerun-if-env-changed={REMOTE_FIXTURES_ENV}");

    let defs: Vec<&AssetDef> = inventory::iter::<AssetDef>.into_iter().collect();
    assert!(
        !defs.is_empty(),
        "kithara-test-fixtures: the asset registry is empty; either `src/defs` declares no \
         `#[kithara::asset]`, or the registrations were dropped at link time",
    );
    for name in defs.iter().flat_map(|def| def.env) {
        println!("cargo:rerun-if-env-changed={name}");
    }
    let resolved = resolve(&defs);

    let fingerprint = fingerprint();
    let namespace = store::namespace(&store::root_from_env(), &fingerprint);
    let unavailable = materialize(&namespace, &resolved);

    // Written once per namespace so its mtime stays put on a no-op rerun; a
    // wiped store makes the declared path missing, which cargo reads as
    // changed and reruns this script.
    let stamp = namespace.join(".stamp");
    if fs::read(&stamp).ok().as_deref() != Some(fingerprint.as_bytes()) {
        fs::write(&stamp, fingerprint.as_bytes())
            .unwrap_or_else(|error| panic!("kithara-test-fixtures: write stamp: {error}"));
    }
    println!("cargo:rerun-if-changed={}", stamp.display());

    let out_dir =
        PathBuf::from(std::env::var_os("OUT_DIR").expect("invariant: cargo always sets OUT_DIR"));
    fs::write(
        out_dir.join("assets.rs"),
        codegen(&namespace, &resolved, &unavailable),
    )
    .unwrap_or_else(|error| panic!("kithara-test-fixtures: write assets.rs: {error}"));
}
