use serde::{Deserialize, Serialize};

use super::{ColorRole, FontSkin, FrameSkin};
use crate::size::SizeSpec;

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
#[non_exhaustive]
pub struct TreeSkin {
    pub size: SizeSpec,
    pub search_placeholder: String,
    pub search_height: f32,
    pub search_icon_width: f32,
    pub search_icon_size: f32,
    pub search_padding_x: f32,
    pub search_text: FontSkin,
    pub search_background: ColorRole,
    pub search_divider: ColorRole,
    pub panel_background: ColorRole,
    pub panel_padding_top: f32,
    pub panel_padding_bottom: f32,
    pub scrollbar_width: f32,
    pub scrollbar_margin: f32,
    pub scroller_color: ColorRole,
    pub scrollbar_background: ColorRole,
    pub row_height: f32,
    pub row_padding_right: f32,
    pub indent_base: f32,
    pub indent_step: f32,
    pub marker_width: f32,
    pub chevron_width: f32,
    pub chevron_size: f32,
    pub icon_size: f32,
    pub content_gap: f32,
    pub label_text: FontSkin,
    pub count_text: FontSkin,
    pub context_height: f32,
    pub context_padding_x: f32,
    pub context_icon_size: f32,
    pub context_gap: f32,
    pub context_text: FontSkin,
    pub context_background: ColorRole,
    pub context_divider: ColorRole,
    pub context_divider_width: f32,
    pub scope_text: FontSkin,
    pub scope_gap: f32,
    pub scope_padding_x: f32,
    pub scope_frame: FrameSkin,
    pub scope_background: ColorRole,
    pub scope_text_color: ColorRole,
    pub scope_chevron_size: f32,
    pub scope_chevron_color: ColorRole,
    pub scope_menu_background: ColorRole,
    pub scope_menu_frame: FrameSkin,
    pub scope_item_height: f32,
    pub scope_menu_text: ColorRole,
    pub scope_selected_background: ColorRole,
    pub scope_selected_text: ColorRole,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
#[non_exhaustive]
pub struct TrackListSkin {
    pub size: SizeSpec,
    pub labels: TrackListLabels,
    pub row_frame: FrameSkin,
    pub deck_chip_frame: FrameSkin,
    pub bpm_badge_frame: FrameSkin,
    pub bpm_badge_background: ColorRole,
    pub divider_color: ColorRole,
    pub divider_hit_width: f32,
    pub divider_width: f32,
    pub energy_bar_background: ColorRole,
    pub cell_padding_x: f32,
    pub footer_padding_x: f32,
    pub grid_gap: f32,
    pub header_height: f32,
    pub row_height: f32,
    pub footer_height: f32,
    pub min_column_width: f32,
    pub index_width: f32,
    pub deck_width: f32,
    pub artist_width: f32,
    pub bpm_width: f32,
    pub key_width: f32,
    pub time_width: f32,
    pub energy_width: f32,
    pub transition_width: f32,
    pub title_min_width: f32,
    pub scrollbar_background: ColorRole,
    pub scrollbar_margin: f32,
    pub scrollbar_width: f32,
    pub scroller_color: ColorRole,
    pub deck_chip_width: f32,
    pub deck_chip_height: f32,
    pub bpm_badge_height: f32,
    pub bpm_badge_padding_x: f32,
    pub energy_bar_width: f32,
    pub energy_bar_height: f32,
    pub energy_bar_gap: f32,
    pub header_text: FontSkin,
    pub index_text: FontSkin,
    pub deck_text: FontSkin,
    pub title_text: FontSkin,
    pub artist_text: FontSkin,
    pub bpm_text: FontSkin,
    pub key_text: FontSkin,
    pub time_text: FontSkin,
    pub energy_text: FontSkin,
    pub transition_text: FontSkin,
    pub footer_text: FontSkin,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
#[non_exhaustive]
pub struct TrackListLabels {
    pub index: String,
    pub deck: String,
    pub title: String,
    pub artist: String,
    pub bpm: String,
    pub key: String,
    pub time: String,
    pub energy: String,
    pub transition: String,
    pub footer_tracks: String,
}
