// @generated by `just tooling xtask config project`; do not edit.
use kithara::play::{EqBandConfig, FilterKind, GainDb};

/// Filter response applied by one equalizer band.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[cfg_attr(any(feature = "uniffi", feature = "uniffi-web"), derive(uniffi::Enum))]
pub enum FfiEqFilterKind {
    LowShelf,
    Peaking,
    HighShelf,
}

/// Configuration for a single EQ band.
#[derive(Clone, Debug, PartialEq)]
#[cfg_attr(
    any(feature = "uniffi", feature = "uniffi-web"),
    derive(uniffi::Record)
)]
pub struct FfiEqBandConfig {
    /// Filter response applied by this band.
    pub kind: FfiEqFilterKind,
    /// Signed band gain in decibels.
    pub gain_db: f32,
    /// Center or cutoff frequency in hertz.
    pub frequency: f32,
    /// Dimensionless quality factor controlling filter bandwidth.
    pub q_factor: f32,
}

impl From<FfiEqBandConfig> for EqBandConfig {
    fn from(value: FfiEqBandConfig) -> Self {
        Self::builder()
            .kind(match value.kind {
                FfiEqFilterKind::LowShelf => FilterKind::LowShelf,
                FfiEqFilterKind::Peaking => FilterKind::Peaking,
                FfiEqFilterKind::HighShelf => FilterKind::HighShelf,
            })
            .gain_db(GainDb::from(value.gain_db))
            .frequency(value.frequency)
            .q_factor(value.q_factor)
            .build()
    }
}

/// Output ceiling and gain recovery of one `PeakLimiter`.
#[derive(Clone, Copy, Debug, PartialEq)]
#[cfg_attr(
    any(feature = "uniffi", feature = "uniffi-web"),
    derive(uniffi::Record)
)]
#[cfg_attr(target_arch = "wasm32", wasm_bindgen::prelude::wasm_bindgen)]
pub struct FfiLimiterConfig {
    /// Linear peak the output never exceeds, in `(0.0, 1.0]`.
    pub ceiling: f32,
    /// Milliseconds the gain takes to recover toward unity.
    pub release_ms: f32,
}

impl Default for FfiLimiterConfig {
    fn default() -> Self {
        let config = kithara::effects::LimiterConfig::default();
        Self {
            ceiling: config.ceiling(),
            release_ms: config.release_ms(),
        }
    }
}

impl TryFrom<FfiLimiterConfig> for kithara::effects::LimiterConfig {
    type Error = crate::types::FfiError;

    fn try_from(config: FfiLimiterConfig) -> Result<Self, Self::Error> {
        Self::builder()
            .ceiling(config.ceiling)
            .release_ms(config.release_ms)
            .build()
            .map_err(|error| crate::types::FfiError::InvalidArgument {
                reason: error.to_string(),
            })
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
#[cfg_attr(
    any(feature = "uniffi", feature = "uniffi-web"),
    derive(uniffi::Record)
)]
pub struct FfiCrossfadeSettings {
    /// Duration of the overlap in seconds.
    pub duration: f32,
    /// Gain curve used during the overlap.
    pub curve: crate::types::FfiCrossfadeCurve,
    /// Fraction of the full crossfade applied, from zero to one.
    pub depth: f32,
    /// Center of the overlap, strictly between zero and one.
    pub position: f32,
}

impl From<kithara::play::CrossfadeSettings> for FfiCrossfadeSettings {
    fn from(value: kithara::play::CrossfadeSettings) -> Self {
        let values = kithara_config::Config::values(&value);
        Self {
            duration: values.duration,
            curve: match values.curve {
                kithara::play::CrossfadeCurve::Linear => crate::types::FfiCrossfadeCurve::Linear,
                kithara::play::CrossfadeCurve::EqualPower => {
                    crate::types::FfiCrossfadeCurve::EqualPower
                }
                _ => crate::types::FfiCrossfadeCurve::Unknown,
            },
            depth: values.depth,
            position: values.position,
        }
    }
}

impl TryFrom<FfiCrossfadeSettings> for kithara::play::CrossfadeSettings {
    type Error = crate::types::FfiError;

    fn try_from(value: FfiCrossfadeSettings) -> Result<Self, Self::Error> {
        let curve = match value.curve {
            crate::types::FfiCrossfadeCurve::Linear => kithara::play::CrossfadeCurve::Linear,
            crate::types::FfiCrossfadeCurve::EqualPower => {
                kithara::play::CrossfadeCurve::EqualPower
            }
            crate::types::FfiCrossfadeCurve::Unknown => {
                return Err(crate::types::FfiError::InvalidArgument {
                    reason: "unknown crossfade curve".into(),
                });
            }
        };
        Self::new(value.duration, curve, value.depth, value.position)
            .map_err(crate::types::FfiError::from)
    }
}
