// @generated by `just tooling xtask config project`; do not edit.
use kithara::play::{EqBandConfig, FilterKind, GainDb};

/// Filter response applied by one equalizer band.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "uniffi", derive(uniffi::Enum))]
pub enum FfiEqFilterKind {
    LowShelf,
    Peaking,
    HighShelf,
}

/// Configuration for a single EQ band.
#[derive(Clone, Debug, PartialEq)]
#[cfg_attr(feature = "uniffi", derive(uniffi::Record))]
pub struct FfiEqBandConfig {
    /// Filter response applied by this band.
    pub kind: FfiEqFilterKind,
    /// Signed band gain in decibels.
    pub gain_db: f32,
    /// Center or cutoff frequency in hertz.
    pub frequency: f32,
    /// Dimensionless quality factor controlling filter bandwidth.
    pub q_factor: f32,
}

impl From<FfiEqBandConfig> for EqBandConfig {
    fn from(value: FfiEqBandConfig) -> Self {
        Self::builder()
            .kind(match value.kind {
                FfiEqFilterKind::LowShelf => FilterKind::LowShelf,
                FfiEqFilterKind::Peaking => FilterKind::Peaking,
                FfiEqFilterKind::HighShelf => FilterKind::HighShelf,
            })
            .gain_db(GainDb::from(value.gain_db))
            .frequency(value.frequency)
            .q_factor(value.q_factor)
            .build()
    }
}

/// Output ceiling and gain recovery of one `PeakLimiter`.
#[derive(Clone, Copy, Debug, PartialEq)]
#[cfg_attr(
    any(feature = "uniffi", feature = "uniffi-web"),
    derive(uniffi::Record)
)]
#[cfg_attr(target_arch = "wasm32", wasm_bindgen::prelude::wasm_bindgen)]
pub struct FfiLimiterConfig {
    /// Linear peak the output never exceeds, in `(0.0, 1.0]`.
    pub ceiling: f32,
    /// Milliseconds the gain takes to recover toward unity.
    pub release_ms: f32,
}
